<a href="https://colab.research.google.com/github/Myriam0402/AlalisisdeDatos/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
juegos=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/VGSales.csv")
juegos

Mounted at /content/drive

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,90,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.0,0.08,7.81
1,240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.0,0.05,4.50
2,259,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.0,0.05,4.31
3,545,Missile Command,2600,1980.0,Shooter,Atari,2.56,0.17,0.0,0.03,2.76
4,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.0,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16593,16533,Sébastien Loeb Rally Evo,XOne,2016.0,Racing,Milestone S.r.l,0.00,0.01,0.0,0.00,0.01
16594,16534,Hitman (2016),XOne,2016.0,Action,Square Enix,0.00,0.01,0.0,0.00,0.01
16595,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.0,0.00,0.01
16596,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.0,0.00,0.01
16597,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.0,0.00,0.01

In [ ]:
juegos.columns

Index(['Rank', 'Nombre', 'Plataforma', 'Year', 'Genre', 'Publisher',
       'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [ ]:
juegos["Genre"].

AttributeError: ignored

In [32]:
#Contar por grupo cuántos juegos son por
#plataforma y genero únicamente Acción y Aventura
Ejercicio1=juegos[((juegos["Genre"]=="Action")|(juegos["Genre"]=="Adventure"))]
Ejercicio1.groupby(["Plataforma","Genre"]).count()

                      Rank  Nombre  Year  Publisher  NA_Sales  EU_Sales  \
Plataforma Genre
2600       Action       61      61    55         61        61        61
           Adventure     2       2     1          2         2         2
3DO        Adventure     1       1     1          1         1         1
3DS        Action      182     182   180        182       182       182
           Adventure    37      37    36         37        37        37
DC         Action        3       3     3          3         3         3
           Adventure    11      11    11         11        11        11
DS         Action      343     343   336        341       343       343
           Adventure   240     240   238        240       240       240
GB         Action        6       6     6          6         6         6
           Adventure     5       5     5          5         5         5
GBA        Action      167     167   162        166       167       167
           Adventure    38      38    37         37        38        38
GC         Action      101     101    98        101       101       101
           Adventure    20      20    20         20        20        20
GEN        Action        3       3     3          3         3         3
           Adventure     2       2     2          2         2         2
N64        Action       38      38    37         38        38        38
           Adventure     4       4     4          4         4         4
NES        Action       13      13    13         13        13        13
           Adventure     1       1     1          1         1         1
PC         Action      165     165   161        165       165       165
           Adventure    65      65    65         65        65        65
PS         Action      157     157   154        156       157       157
           Adventure    69      69    67         68        69        69
PS2        Action      348     348   345        348       348       348
           Adventure   196     196   196        196       196       196
PS3        Action      380     380   373        380       380       380
           Adventure    74      74    72         73        74        74
PS4        Action      122     122   122        122       122       122
           Adventure    19      19    19         19        19        19
PSP        Action      222     222   217        221       222       222
           Adventure   213     213   213        213       213       213
PSV        Action      142     142   142        141       142       142
           Adventure    86      86    86         85        86        86
SAT        Action        3       3     3          3         3         3
           Adventure    26      26    26         26        26        26
SNES       Action       12      12    12         12        12        12
           Adventure     4       4     4          4         4         4
TG16       Adventure     1       1     1          1         1         1
Wii        Action      238     238   230        237       238       238
           Adventure    84      84    83         84        84        84
WiiU       Action       63      63    63         63        63        63
           Adventure     3       3     3          3         3         3
X360       Action      324     324   318        324       324       324
           Adventure    47      47    47         47        47        47
XB         Action      155     155   152        155       155       155
           Adventure    26      26    26         26        26        26
XOne       Action       68      68    68         68        68        68
           Adventure    12      12    12         12        12        12

                      JP_Sales  Other_Sales  Global_Sales
Plataforma Genre
2600       Action           61           61            61
           Adventure         2            2             2
3DO        Adventure         1            1             1
3DS        Action          182          182           182
           Adventure        37           37            37
DC         Action            3            3             3
           Adventure        11           11            11
DS         Action          343          343           343
           Adventure       240          240           240
GB         Action            6            6             6
           Adventure         5            5             5
GBA        Action          167          167           167
           Adventure        38           38            38
GC         Action          101          101           101
           Adventure        20           20            20
GEN        Action            3            3             3
           Adventure         2            2             2
N64        Action           38           38            38
           Adventure         4            4             4
NES        Action           13           13            13
           Adventure         1            1             1
PC         Action          165          165           165
           Adventure        65           65            65
PS         Action          157          157           157
           Adventure        69           69            69
PS2        Action          348          348           348
           Adventure       196          196           196
PS3        Action          380          380           380
           Adventure        74           74            74
PS4        Action          122          122           122
           Adventure        19           19            19
PSP        Action          222          222           222
           Adventure       213          213           213
PSV        Action          142          142           142
           Adventure        86           86            86
SAT        Action            3            3             3
           Adventure        26           26            26
SNES       Action           12           12            12
           Adventure         4            4             4
TG16       Adventure         1            1             1
Wii        Action          238          238           238
           Adventure        84           84            84
WiiU       Action           63           63            63
           Adventure         3            3             3
X360       Action          324          324           324
           Adventure        47           47            47
XB         Action          155          155           155
           Adventure        26           26            26
XOne       Action           68           68            68
           Adventure        12           12            12

In [ ]:
#Contar por grupos cuántos juegos son por género y año únicamente
#de los años 2010 y superiores
Ejercicio2=juegos[((juegos["Year"]>=2010))].groupby(["Genre","Year"]).count()
Ejercicio2

                 Rank  Nombre  Plataforma  Publisher  NA_Sales  EU_Sales  \
Genre    Year
Action   2010.0   226     226         226        226       226       226
         2011.0   239     239         239        239       239       239
         2012.0   266     266         266        265       266       266
         2013.0   148     148         148        148       148       148
         2014.0   186     186         186        186       186       186
...               ...     ...         ...        ...       ...       ...
Strategy 2012.0    15      15          15         15        15        15
         2013.0    19      19          19         19        19        19
         2014.0     8       8           8          8         8         8
         2015.0    17      17          17         17        17        17
         2016.0    10      10          10         10        10        10

                 JP_Sales  Other_Sales  Global_Sales
Genre    Year
Action   2010.0       226          226           226
         2011.0       239          239           239
         2012.0       266          266           266
         2013.0       148          148           148
         2014.0       186          186           186
...                   ...          ...           ...
Strategy 2012.0        15           15            15
         2013.0        19           19            19
         2014.0         8            8             8
         2015.0        17           17            17
         2016.0        10           10            10

[86 rows x 9 columns]

In [30]:
#Agrupar y sumar las ventas globales por género
#sum en ventas globales
Ejercicio3= juegos[["Global_Sales","Genre"]].groupby("Genre")["Global_Sales"].sum()
Ejercicio3

Genre
Action          1751.18
Adventure        239.04
Fighting         448.91
Misc             809.96
Platform         831.37
Puzzle           244.95
Racing           732.04
Role-Playing     927.37
Shooter         1037.37
Simulation       392.20
Sports          1330.93
Strategy         175.12
Name: Global_Sales, dtype: float64

In [ ]:
3